### ISSUE TITLE
Unpaid break length broken for multiple breaks

### ISSUE THREAD

**Issue by mehtaamish89** [joshmedeski/wheniwork-cli#16]
The unpaid breaks length calculation is broken when there are more than one unpaid breaks. 

For the second unpaid break, it considers the first breaks `OUT` time.
E.g.:-

![image](https://user-images.githubusercontent.com/12073764/45392083-57d02180-b5eb-11e8-946d-21ccc1df4651.png)

**Comment by joshmedeski** [comment]
Duplicate of #5
